export const ASK_RECOMMENDATION_DOCS = {
  SUMMARY: 'Generate Cattle Farming Recommendation',
  DESCRIPTION:
    'Uses Gemini + Chroma retrieval to generate persistent chat responses for cattle farmers while storing the conversation history in the database.',
  OPERATION_ID: 'askRecommendation',
  REQUEST: {
    NAME: 'AskRecommendationRequest',
    DESCRIPTION: 'Contains the user question, optional retrieval depth, and an optional chat identifier to continue a conversation.',
    FIELDS: {
      QUESTION: 'Question from the farmer or advisor about livestock, feeding, pasture, health, productivity, or management.',
      LIMIT: 'Maximum number of similar Chroma chunks used as context (between 1 and 10).',
      CHAT_ID: 'Optional chat identifier used to continue a persistent conversation.',
    },
  },
  RESPONSE: {
    NAME: 'AskRecommendationResponse',
    DESCRIPTION: 'Contains the AI recommendation, the retrieved context, and the persisted chat history used to build it.',
    FIELDS: {
      CHAT_ID: 'Persistent chat identifier stored in the database.',
      AI_ANSWER: 'Final recommendation generated by Gemini grounded on the retrieved context.',
      CONTEXTS: 'Retrieved context entries returned by Chroma and used in the prompt.',
      MESSAGES: 'Ordered chat messages persisted for the current conversation.',
    },
  },
  CONTEXT: {
    NAME: 'RecommendationContextItem',
    DESCRIPTION:
      'Represents a single context chunk retrieved from ChromaDB, which may include the original question, answer, source document, and similarity distance.',
    FIELDS: {
      ID: 'Unique identifier of the retrieved record in Chroma.',
      QUESTION: 'Original question text stored in record metadata when available.',
      ANSWER: 'Original answer text stored in record metadata when available.',
      TAGS: 'Optional tags stored in record metadata when available.',
      DOCUMENT: 'Raw retrieved document as stored in Chroma.',
      DISTANCE: 'Similarity distance returned by Chroma (lower is usually closer).',
    },
  },
  MESSAGE: {
    NAME: 'RecommendationMessageItem',
    DESCRIPTION: 'Represents a single persisted chat message within a recommendation conversation.',
    FIELDS: {
      ROLE: 'Message author within the conversation, either user or assistant.',
      CONTENT: 'Message content saved in the database.',
      CREATED_AT: 'ISO timestamp indicating when the message was stored.',
    },
  },
  RESULTS: {
    OK: 'Recommendation chat generated successfully.',
    UNAUTHORIZED: 'Authentication token is missing, invalid, or the user has no client profile.',
    NOT_FOUND: 'The requested chat does not exist or does not belong to the authenticated user.',
    UNPROCESSABLE_ENTITY: 'Request body validation failed.',
    SERVICE_UNAVAILABLE: 'The AI service is unavailable or not configured.',
  },
} as const;

export const ASK_RECOMMENDATION_STREAM_DOCS = {
  SUMMARY: 'Stream Cattle Farming Recommendation',
  DESCRIPTION:
    'Provides a real-time stream of events for generating persistent cattle farming recommendations, including the chat identifier, metadata about the query and context, progressive content chunks of the recommendation, and completion or error notifications.',
  OPERATION_ID: 'askRecommendationStream',
  METADATA_EVENT: {
    NAME: 'AskRecommendationStreamMetadataEvent',
    DESCRIPTION: 'Emitted once at the beginning of the stream, containing the chat identifier, original question, and retrieved context.',
    FIELDS: {
      TYPE: 'Discriminant field with value "metadata" to identify this event type.',
      CHAT_ID: 'Persistent chat identifier stored in the database.',
      QUERY: 'The original question sent by the user.',
      METADATA: 'Array of context items retrieved from Chroma used to generate the recommendation.',
    },
  },
  CONTENT_EVENT: {
    NAME: 'AskRecommendationStreamContentEvent',
    DESCRIPTION: 'Emitted one or more times containing chunks of the generated recommendation as they are produced by Gemini.',
    FIELDS: {
      TYPE: 'Discriminant field with value "content" to identify this event type.',
      CHUNK: 'A partial chunk of the AI-generated recommendation text.',
    },
  },
  DONE_EVENT: {
    NAME: 'AskRecommendationStreamDoneEvent',
    DESCRIPTION: 'Emitted once at the end of the stream to indicate that the chat recommendation generation is complete.',
    FIELDS: {
      TYPE: 'Discriminant field with value "done" to identify this event type.',
      CHAT_ID: 'Persistent chat identifier stored in the database.',
    },
  },
  ERROR_EVENT: {
    NAME: 'AskRecommendationStreamErrorEvent',
    DESCRIPTION: 'Emitted if an error occurs during processing, containing an error message.',
    FIELDS: {
      TYPE: 'Discriminant field with value "error" to identify this event type.',
      ERROR: 'Error message describing what went wrong.',
    },
  },
  EVENT_FLOW:
    'Stream sequence: 1) metadata event (once) → 2) content events (multiple, progressive) → 3) done event (once) OR error event (on error)',
  RESULTS: {
    UNAUTHORIZED: 'Authentication token is missing, invalid, or the user has no client profile.',
    NOT_FOUND: 'The requested chat does not exist or does not belong to the authenticated user.',
    UNPROCESSABLE_ENTITY: 'Request body validation failed.',
    SERVICE_UNAVAILABLE: 'The AI service is unavailable or not configured.',
  },
} as const;
