export const AUTH_ERROR_CODES = {
  TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
  TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  TOKEN_NOT_FOUND: 'AUTH.TOKEN_NOT_FOUND',
  TOKENS_ALREADY_LINKED: 'AUTH.TOKENS_ALREADY_LINKED',
  PASSWORD_INVALID: 'AUTH.PASSWORD_INVALID',
  PASSWORD_REQUIRED: 'AUTH.PASSWORD_REQUIRED',
  PASSWORD_FORBIDDEN: 'AUTH.PASSWORD_FORBIDDEN',
  PASSWORD_RESET_PENDING: 'AUTH.PASSWORD_RESET_PENDING',
  PASSWORD_SAME_AS_CURRENT: 'AUTH.PASSWORD_SAME_AS_CURRENT',
  MFA_TOKEN_INVALID: 'AUTH.MFA_TOKEN_INVALID',
  MFA_REQUIRED: 'AUTH.MFA_REQUIRED',
  MFA_ALREADY_ENABLED: 'AUTH.MFA_ALREADY_ENABLED',
  MFA_REGENERATION_RATE_LIMITED: 'AUTH.MFA_REGENERATION_RATE_LIMITED',
  ROLE_INSUFFICIENT: 'AUTH.ROLE_INSUFFICIENT',
  ROLE_NOT_FOUND: 'AUTH.ROLE_NOT_FOUND',
  CLIENT_NOT_FOUND: 'AUTH.CLIENT_NOT_FOUND',
  USER_NOT_FOUND: 'AUTH.USER_NOT_FOUND',
  USER_EXTERNAL_REQUIRED: 'AUTH.USER_EXTERNAL_REQUIRED',
  USER_ALREADY_EXISTS: 'AUTH.USER_ALREADY_EXISTS',
  EMAIL_MISSING: 'AUTH.EMAIL_MISSING',
  EMAIL_ALREADY_IN_USE: 'AUTH.EMAIL_ALREADY_IN_USE',
  EMAIL_NOT_VERIFIED: 'AUTH.EMAIL_NOT_VERIFIED',
  GOOGLE_TOKEN_INVALID: 'AUTH.GOOGLE_TOKEN_INVALID',
  APPLE_TOKEN_INVALID: 'AUTH.APPLE_TOKEN_INVALID',
  OTP_SESSION_INVALID: 'AUTH.OTP_SESSION_INVALID',
  SESSION_LOG_NOT_FOUND: 'AUTH.SESSION_LOG_NOT_FOUND',
} as const;

export const RECOMMENDATIONS_ERROR_CODES = {
  CHAT_NOT_FOUND: 'RECOMMENDATIONS.CHAT_NOT_FOUND',
  CHAT_NO_CHANGES: 'RECOMMENDATIONS.CHAT_NO_CHANGES',
  AI_GENERATION_FAILED: 'RECOMMENDATIONS.AI_GENERATION_FAILED',
  CONTEXT_NOT_FOUND: 'RECOMMENDATIONS.CONTEXT_NOT_FOUND',
  CONTEXT_NO_CHANGES: 'RECOMMENDATIONS.CONTEXT_NO_CHANGES',
} as const;

export const USERS_ERROR_CODES = {
  CLIENT_ALREADY_EXISTS: 'USERS.CLIENT_ALREADY_EXISTS',
  CLIENT_NOT_FOUND: 'USERS.CLIENT_NOT_FOUND',
  CLIENT_NO_CHANGES: 'USERS.CLIENT_NO_CHANGES',
  USER_NOT_FOUND: 'USERS.USER_NOT_FOUND',
  USER_NOT_DELETED: 'USERS.USER_NOT_DELETED',
  USER_NO_CHANGES: 'USERS.USER_NO_CHANGES',
  USERNAME_ALREADY_IN_USE: 'USERS.USERNAME_ALREADY_IN_USE',
  PROFILE_PICTURE_NOT_FOUND: 'USERS.PROFILE_PICTURE_NOT_FOUND',
  PROFILE_PICTURE_PROCESSING: 'USERS.PROFILE_PICTURE_PROCESSING',
  RECOVERY_TOKEN_ALREADY_SENT: 'USERS.RECOVERY_TOKEN_ALREADY_SENT',
  RECOVERY_TOKEN_NOT_FOUND: 'USERS.RECOVERY_TOKEN_NOT_FOUND',
  RECOVERY_TOKEN_EXPIRED: 'USERS.RECOVERY_TOKEN_EXPIRED',
} as const;

export const GENERIC_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'GENERIC.INTERNAL_SERVER_ERROR',
  INVALID_INPUT: 'GENERIC.INVALID_INPUT',
  THROTTLED: 'GENERIC.THROTTLED',
  NOT_FOUND: 'GENERIC.NOT_FOUND',
} as const;

export type ErrorCode =
  | (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES]
  | (typeof RECOMMENDATIONS_ERROR_CODES)[keyof typeof RECOMMENDATIONS_ERROR_CODES]
  | (typeof USERS_ERROR_CODES)[keyof typeof USERS_ERROR_CODES]
  | (typeof GENERIC_ERROR_CODES)[keyof typeof GENERIC_ERROR_CODES];
